name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: js-drumKit
          path: '.'  # Adjust the path as needed
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
